name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - next

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    name: Release
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.get-release-tag.outputs.tag_name }}
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies ⏬
        run: npm ci

      - name: Build artifacts 🏗️
        run: npm run build

      - id: semantic-release-step
        name: Release with Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - id: get-release-tag
        name: Determine released version 🔖
        run: |
          TAG_NAME=$(git tag --points-at HEAD)
          echo "tag_name=${TAG_NAME}" >> "$GITHUB_OUTPUT"

  discord-notification:
    name: Discord notification
    needs: release
    if: needs.release.outputs.tag_name != ''
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification 📯
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.4.0
        with:
          args: '${{ github.event.repository.name }} [${{ needs.release.outputs.tag_name }}](${{ github.event.repository.html_url }}/releases/tag/${{ needs.release.outputs.tag_name }}) has been released. 🚀'
